// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace bid
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinClient uI额度投标网络客户端模拟程序Client = this.UI额度投标网络客户端模拟程序Window.UI额度投标网络客户端模拟程序Client;
            WinClient uI额度投标网络客户端Client = this.UI额度投标网络客户端Window.UI额度投标网络客户端Client;
            WinEdit uIItemEdit = this.UI额度投标网络客户端模拟程序Window.UIItemWindow.UIItemEdit;
            WinEdit uIItemEdit1 = this.UI额度投标网络客户端模拟程序Window.UIItemWindow1.UIItemEdit;
            WinEdit uIItemEdit2 = this.UI额度投标网络客户端模拟程序Window.UIItemWindow2.UIItemEdit;
            WinEdit uIItemEdit3 = this.UI额度投标网络客户端模拟程序Window1.UIItemWindow.UIItemEdit;
            WinEdit uIItemEdit4 = this.UI额度投标网络客户端模拟程序Window1.UIItemWindow1.UIItemEdit;
            WinClient uI额度投标网络客户端模拟程序Client1 = this.UI额度投标网络客户端模拟程序Window1.UI额度投标网络客户端模拟程序Client;
            WinEdit uIItemEdit5 = this.UI额度投标网络客户端Window1.UIItemWindow.UIItemEdit;
            WinClient uI额度投标网络客户端Client1 = this.UI额度投标网络客户端Window1.UI额度投标网络客户端Client;
            #endregion

            // Click '额度投标网络客户端---模拟程序' client
            Mouse.Click(uI额度投标网络客户端模拟程序Client, new Point(231, 279));

            // Click '额度投标网络客户端' client
            Mouse.Click(uI额度投标网络客户端Client, new Point(247, 233));

            // Type '11111111' in text box
            uIItemEdit.Text = this.RecordedMethod1Params.UIItemEditText;

            // Move text box to '额度投标网络客户端---模拟程序' client
            uI额度投标网络客户端模拟程序Client.EnsureClickable(new Point(519, 357));
            Mouse.StartDragging(uIItemEdit1, new Point(55, 12));
            Mouse.StopDragging(uI额度投标网络客户端模拟程序Client, new Point(519, 357));

            // Type '********' in text box
            Keyboard.SendKeys(uIItemEdit1, this.RecordedMethod1Params.UIItemEditSendKeys, true);

            // Type '586135' in text box
            uIItemEdit2.Text = this.RecordedMethod1Params.UIItemEditText1;

            // Click '额度投标网络客户端---模拟程序' client
            Mouse.Click(uI额度投标网络客户端模拟程序Client, new Point(648, 505));

            // Type '100' in text box
            uIItemEdit3.Text = this.RecordedMethod1Params.UIItemEditText2;

            // Type '100' in text box
            uIItemEdit4.Text = this.RecordedMethod1Params.UIItemEditText3;

            // Click '额度投标网络客户端---模拟程序' client
            Mouse.Click(uI额度投标网络客户端模拟程序Client1, new Point(850, 380));

            // Type '038078' in text box
            uIItemEdit5.Text = this.RecordedMethod1Params.UIItemEditText4;

            // Click '额度投标网络客户端' client
            Mouse.Click(uI额度投标网络客户端Client1, new Point(162, 222));

            // Click '额度投标网络客户端' client
            Mouse.Click(uI额度投标网络客户端Client, new Point(217, 230));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UI额度投标网络客户端模拟程序Window UI额度投标网络客户端模拟程序Window
        {
            get
            {
                if ((this.mUI额度投标网络客户端模拟程序Window == null))
                {
                    this.mUI额度投标网络客户端模拟程序Window = new UI额度投标网络客户端模拟程序Window();
                }
                return this.mUI额度投标网络客户端模拟程序Window;
            }
        }
        
        public UI额度投标网络客户端Window UI额度投标网络客户端Window
        {
            get
            {
                if ((this.mUI额度投标网络客户端Window == null))
                {
                    this.mUI额度投标网络客户端Window = new UI额度投标网络客户端Window();
                }
                return this.mUI额度投标网络客户端Window;
            }
        }
        
        public UI额度投标网络客户端模拟程序Window1 UI额度投标网络客户端模拟程序Window1
        {
            get
            {
                if ((this.mUI额度投标网络客户端模拟程序Window1 == null))
                {
                    this.mUI额度投标网络客户端模拟程序Window1 = new UI额度投标网络客户端模拟程序Window1();
                }
                return this.mUI额度投标网络客户端模拟程序Window1;
            }
        }
        
        public UI额度投标网络客户端Window1 UI额度投标网络客户端Window1
        {
            get
            {
                if ((this.mUI额度投标网络客户端Window1 == null))
                {
                    this.mUI额度投标网络客户端Window1 = new UI额度投标网络客户端Window1();
                }
                return this.mUI额度投标网络客户端Window1;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UI额度投标网络客户端模拟程序Window mUI额度投标网络客户端模拟程序Window;
        
        private UI额度投标网络客户端Window mUI额度投标网络客户端Window;
        
        private UI额度投标网络客户端模拟程序Window1 mUI额度投标网络客户端模拟程序Window1;
        
        private UI额度投标网络客户端Window1 mUI额度投标网络客户端Window1;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '11111111' in text box
        /// </summary>
        public string UIItemEditText = "11111111";
        
        /// <summary>
        /// Type '********' in text box
        /// </summary>
        public string UIItemEditSendKeys = "I1Tbta0jzhrd6T9M62YK4lqYaz6wDthT";
        
        /// <summary>
        /// Type '586135' in text box
        /// </summary>
        public string UIItemEditText1 = "586135";
        
        /// <summary>
        /// Type '100' in text box
        /// </summary>
        public string UIItemEditText2 = "100";
        
        /// <summary>
        /// Type '100' in text box
        /// </summary>
        public string UIItemEditText3 = "100";
        
        /// <summary>
        /// Type '038078' in text box
        /// </summary>
        public string UIItemEditText4 = "038078";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UI额度投标网络客户端模拟程序Window : WinWindow
    {
        
        public UI额度投标网络客户端模拟程序Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "额度投标网络客户端---模拟程序";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TLoginForm";
            this.WindowTitles.Add("额度投标网络客户端---模拟程序");
            #endregion
        }
        
        #region Properties
        public WinClient UI额度投标网络客户端模拟程序Client
        {
            get
            {
                if ((this.mUI额度投标网络客户端模拟程序Client == null))
                {
                    this.mUI额度投标网络客户端模拟程序Client = new WinClient(this);
                    #region Search Criteria
                    this.mUI额度投标网络客户端模拟程序Client.SearchProperties[WinControl.PropertyNames.Name] = "额度投标网络客户端---模拟程序";
                    this.mUI额度投标网络客户端模拟程序Client.WindowTitles.Add("额度投标网络客户端---模拟程序");
                    #endregion
                }
                return this.mUI额度投标网络客户端模拟程序Client;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow2 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow2(this);
                }
                return this.mUIItemWindow2;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUI额度投标网络客户端模拟程序Client;
        
        private UIItemWindow mUIItemWindow;
        
        private UIItemWindow1 mUIItemWindow1;
        
        private UIItemWindow2 mUIItemWindow2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("额度投标网络客户端---模拟程序");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("额度投标网络客户端---模拟程序");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TEdit";
            this.WindowTitles.Add("额度投标网络客户端---模拟程序");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("额度投标网络客户端---模拟程序");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            this.WindowTitles.Add("额度投标网络客户端---模拟程序");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("额度投标网络客户端---模拟程序");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UI额度投标网络客户端Window : WinWindow
    {
        
        public UI额度投标网络客户端Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "额度投标网络客户端";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TErrorBoxForm";
            this.WindowTitles.Add("额度投标网络客户端");
            #endregion
        }
        
        #region Properties
        public WinClient UI额度投标网络客户端Client
        {
            get
            {
                if ((this.mUI额度投标网络客户端Client == null))
                {
                    this.mUI额度投标网络客户端Client = new WinClient(this);
                    #region Search Criteria
                    this.mUI额度投标网络客户端Client.SearchProperties[WinControl.PropertyNames.Name] = "额度投标网络客户端";
                    this.mUI额度投标网络客户端Client.WindowTitles.Add("额度投标网络客户端");
                    #endregion
                }
                return this.mUI额度投标网络客户端Client;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUI额度投标网络客户端Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UI额度投标网络客户端模拟程序Window1 : WinWindow
    {
        
        public UI额度投标网络客户端模拟程序Window1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "额度投标网络客户端---模拟程序";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMainForm";
            this.WindowTitles.Add("额度投标网络客户端---模拟程序");
            #endregion
        }
        
        #region Properties
        public UIItemWindow3 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow3(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public WinClient UI额度投标网络客户端模拟程序Client
        {
            get
            {
                if ((this.mUI额度投标网络客户端模拟程序Client == null))
                {
                    this.mUI额度投标网络客户端模拟程序Client = new WinClient(this);
                    #region Search Criteria
                    this.mUI额度投标网络客户端模拟程序Client.SearchProperties[WinControl.PropertyNames.Name] = "额度投标网络客户端---模拟程序";
                    this.mUI额度投标网络客户端模拟程序Client.WindowTitles.Add("额度投标网络客户端---模拟程序");
                    #endregion
                }
                return this.mUI额度投标网络客户端模拟程序Client;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow3 mUIItemWindow;
        
        private UIItemWindow11 mUIItemWindow1;
        
        private WinClient mUI额度投标网络客户端模拟程序Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TEdit";
            this.WindowTitles.Add("额度投标网络客户端---模拟程序");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("额度投标网络客户端---模拟程序");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("额度投标网络客户端---模拟程序");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("额度投标网络客户端---模拟程序");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UI额度投标网络客户端Window1 : WinWindow
    {
        
        public UI额度投标网络客户端Window1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "额度投标网络客户端";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TImageForm";
            this.WindowTitles.Add("额度投标网络客户端");
            #endregion
        }
        
        #region Properties
        public UIItemWindow4 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow4(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public WinClient UI额度投标网络客户端Client
        {
            get
            {
                if ((this.mUI额度投标网络客户端Client == null))
                {
                    this.mUI额度投标网络客户端Client = new WinClient(this);
                    #region Search Criteria
                    this.mUI额度投标网络客户端Client.SearchProperties[WinControl.PropertyNames.Name] = "额度投标网络客户端";
                    this.mUI额度投标网络客户端Client.WindowTitles.Add("额度投标网络客户端");
                    #endregion
                }
                return this.mUI额度投标网络客户端Client;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow4 mUIItemWindow;
        
        private WinClient mUI额度投标网络客户端Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow4 : WinWindow
    {
        
        public UIItemWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TEdit";
            this.WindowTitles.Add("额度投标网络客户端");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("额度投标网络客户端");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
}
